[package]
name = "saba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noli = { git = "https://github.com/hikalium/wasabi.git", branch = "for_saba", version = "0.1.0" }
